### ISSUE TITLE
Standardise video component

### ISSUE THREAD

**Issue by expe** [Financial-Times/o-video#1]
We would like to create a standard video component which can be used on FT branded and non-branded sites.

Next has already created a video player which we can probably base o-video off:
https://github.com/Financial-Times/n-video

**Thoughts**
- The Next component has functionality for YouTube etc. By the looks of it, all videos on FT sites are using Brightcove. Do we want to standardise on Brightcove?
- HTML5 video should be default.
- Do we support core experience? i.e. Transcript.
- We could have a default playlist style or make it scriptable.

Would be good to get opinions from IG and Next
@kavanagh @ironsidevsquincy

Also https://live.ft.com has videos.

**Comment by AlbertoElias** [comment]
This is now done
