### ISSUE TITLE
oVideo to support slot level override of config (mix and match global + data attribute config)

### ISSUE THREAD

**Issue by VladDubrovskis** [Financial-Times/o-video#12]
At the moment it seems like you can init multiple videos only if all of your options are either in the data attributes, or in the config passed to init function, there is no way to use both of them.

Tried to add the feature but that seem to have created more issues with the multiple videos on same age where all videos on page would have same placeholder? That might have been a side effect of the requested feature.

**Comment by chee** [comment]
it would appear that options from the data attributes are now merged with the options from the config object:

https://github.com/Financial-Times/o-video/blob/a98b4421bcf5898196d8c36504568f67a1151adf/src/js/video.js#L173

if i've overlooked something please re-open
