### ISSUE TITLE
We should track buffering events

### ISSUE THREAD

**Issue by sjparkinson** [Financial-Times/o-video#124]
https://github.com/Financial-Times/o-video/blob/166e5a23df77e08653e286308f8821aad0dbc10d/src/js/video.js#L241

https://developer.mozilla.org/en-US/docs/Web/Events/waiting

Relates to https://trello.com/c/PhYVid5N/276-loading-videos-on-ftcom.

We've _only just_ enabled streaming miss on the next media API's Fastly service, which should have dramatic improvements to the video load times.

**Comment by JakeChampion** [comment]
How is the `waiting` event different from the `stalled` event we already fire?
https://html.spec.whatwg.org/multipage/media.html#event-media-waiting
https://html.spec.whatwg.org/multipage/media.html#event-media-stalled

**Comment by sjparkinson** [comment]
> The stall timeout is a user-agent defined length of time, which should be about three seconds. When a media element that is actively attempting to obtain media data has failed to receive any data for a duration equal to the stall timeout, the user agent must queue a task to fire an event named stalled at the element.

from https://html.spec.whatwg.org/multipage/media.html#loading-the-media-resource:event-media-stalled.

Which to me sounds more about hard errors. Whereas the waiting event is more around performance, how often our users are seeing a spinning circle.
