### ISSUE TITLE
remove h4 heading from o-video

### ISSUE THREAD

**Issue by notlee** [Financial-Times/o-video#170]
The title of o-video is added as a `h4` heading, we should remove it:
1. We cannot assume an `h4` is the correct heading level in context.
2. The video title likely doesn't make sense as a heading in the document context.
3. The heading is removed when the video is played. Just because a video is played, the structure of the document shouldn't change.

**proposed solution**

An option is to make the heading element configurable as [discussed in this Customer Products Jira ticket](https://financialtimes.atlassian.net/browse/DAC-64) but I think that only solves point 1. We should also ensure the heading remains but is visually hidden to solve point 3 also.

But given point 2 and 3, I think we can safely set the element to a `span` in a patch release instead. However as a `span` the title of the video is read out as text by a screen reader in the middle of a page without context. The title is then repeated as part of the play button. To address that we could add `aria-label="Video Player”` to the root `o-video` element which would be read `“Video Player, group“` by VoiceOver; giving useful context when stepping through page content. More details and a gif in the [related Customer Products Jira ticket](https://financialtimes.atlassian.net/browse/DAC-64). More research is needed to check this is a good approach.

**Comment by notlee** [comment]
Note: this is an `AAA` issue so not urgent but something I think we should do

**Comment by JakeChampion** [comment]
> But given point 2 and 3, I think we can safely set the element to a `span` in a patch release instead. However as a `span` the title of the video is read out as text by a screen reader in the middle of a page without context. The title is then repeated as part of the play button. To address that we could add `aria-label="Video Player”` to the root `o-video` element which would be read `“Video Player, group“` by VoiceOver; giving useful context when stepping through page content.

This sounds like the best approach to take.



> More research is needed to check this is a good approach.

What specifically do you think we need to research more on? Testing the solution with other accessibility tooling?

**Comment by notlee** [comment]
>What specifically do you think we need to research more on? Testing the solution with other accessibility tooling?

Yeah. But also are there any standard ways to mark up a video placeholder? Or any better examples to take inspiration from?

**Comment by notlee** [comment]
note to self: would it be better to use `figure` and `figcaption`? https://html.spec.whatwg.org/multipage/grouping-content.html#the-figure-element

**Comment by notlee** [comment]
>note to self: would it be better to use figure and figcaption? https://html.spec.whatwg.org/multipage/grouping-content.html#the-figure-element

maybe not, since again its optional and repeated on the play button

**Comment by notlee** [comment]
we removed the `h4` in v6.0.9 https://github.com/Financial-Times/o-video/pull/175
