### ISSUE TITLE
JSONP request timed out uncaught exception

### ISSUE THREAD

**Issue by petrklus** [Financial-Times/o-video#19]
Hello!

On a recently launched page http://enterprise.ft.com/en-gb/best-of-ft/, I have started to see intermittent errors:

![image](https://cloud.githubusercontent.com/assets/1115667/17398924/a0ce9a24-5a3f-11e6-9cf2-9a99e98c601c.png)

We are using following URL to generate the JS bundle:

https://origami-build.ft.com/v2/bundles/js?modules=o-video@^1.1.1,o-share@^2.1.5,o-footer@^5.0.1,o-fonts@^2.1.2,o-typography@^4.3.0,o-colors@^3.4.1,o-hoverable@^3.0.1,o-buttons@^4.0.1

The video markup is following:

```
<div>
     <div class="o-video video-container" data-o-component="o-video" data-o-video-source="brightcove" data-o-video-id="4762665469001" data-o-video-placeholder="true"></div>
</div>
```

However, the response it seems to be complaining about is received fine (from the Network tab):

Response 200, response content seems fine as well:

https://gist.githubusercontent.com/petrklus/c6801ab449806577689ef92bb7f9857f/raw/87854a2c3de65af7501bf005770919b9d9005ed4/next-video.ft.com%2520api%25204762665469001

The error seems to be coming from the following line (of the unminified JS):

![image](https://cloud.githubusercontent.com/assets/1115667/17399375/0a279992-5a42-11e6-9673-19bea00db77f.png)

![image](https://cloud.githubusercontent.com/assets/1115667/17399387/1b3f512a-5a42-11e6-82ad-090b93d726fb.png)

From https://origami-build.ft.com/v2/bundles/js?modules=o-video@^1.1.1,o-share@^2.1.5,o-footer@^5.0.1,o-fonts@^2.1.2,o-typography@^4.3.0,o-colors@^3.4.1,o-hoverable@^3.0.1,o-buttons@^4.0.1&minify=none

It's a bit tricky to reproduce - it seems to be happening intermittently and cannot seem to be able to pinpoint exact scenario how to reliably reproduce it.

When the error is thrown, the affected video is not rendered:

![image](https://cloud.githubusercontent.com/assets/1115667/17399349/e4527688-5a41-11e6-880d-0ded97c42f74.png)

The same issue happens both on the live page and in local development.

Lastly, seeing the issue with Chrome Version 51.0.2704.103 (64-bit) but we now saw it throughout other browsers as well.

**Comment by petrklus** [comment]
@AlbertoElias would you be able to help with this please?

**Comment by AlbertoElias** [comment]
I don't know much about this. @wheresrhys would you know what might be going on or who worked on next-video?

**Comment by wheresrhys** [comment]
This is just what it says - a timed out response. the default timeout in o-jsonp is 2seconds. I can suggest 2 changes in o-video to deal wit this
1. Increase/remove the timeout - 2 seconds does seem a bit strict. Also maybe allow o-video users to set the timeout to whatever is appropriate for their product (e.g. on a video hub page you'd want to wait longer than if you're just loading supplementary content on an article)
2. Fail in a more user friendly way e.g. if timed out show a message 'video failed to load' with a 'try again' button

I plan on turning next-video into a faster, simpler proxy through to brightcove, but need to decouple some other things from it first

**Comment by petrklus** [comment]
Hello @wheresrhys !

I was wondering if there was any update on this issue?

**Comment by wheresrhys** [comment]
> I plan on turning next-video into a faster, simpler proxy through to brightcove, but need to decouple some other things from it first

Investigated a while ago, but impossible while we still support ie9 (as need to upport jsonp). Now ie9 has dropped down the FT browser support list it shoudl be possible to improve the server response times a bit. But not high priority

But it's still something the component could cope better with, but I don't work on the component

**Comment by notlee** [comment]
Closing this old issue. We've since removed jsonp support. Please feel free to reopen if this issue has persisted.
