### ISSUE TITLE
Move o-video advertising code to o-ads

### ISSUE THREAD

**Issue by VladDubrovskis** [Financial-Times/o-video#28]
**Background**
Origami has got the following 2 components:
`o-video` - responsible for video playback from Brightcove
`o-ads` - responsible for advertising configuration of slots

Historically `o-ads` used to have video advertising targeting for Brightcove player in the module, which has been removed as we use a native player now.

At the moment `o-video` is responsible for video advertising.

**Proposal**
Find a way to make `o-ads` and `o-video` work together. The benefit and in fact a requirement of it would be that if a site is using `o-ads` module, and wish to implement `o-video`, the site owner can use the same targeting that they have got in `o-ads`. At the moment `o-video` targeting is limited, and making all of the targeting work would just duplicate the efforts.

**Solutions/ideas**

_Idea 1:_
Move the video advertising code from `o-video` to `o-ads`
Any video specific targeting could be added to "data-attributes"
`o-ads` would either have an event listener for "play" when video starts
`o-video` could emit an event once video has been initiated and `o-ads` could act on that event to make the ad call (this hopefully preventing any race conditions happening)
The only theoretical race condition that might happen is that `o-ads` is not initialised before the `o-video` init event has been emitted, which will result in no ad served vs any degradation to user experience.

_Idea 2:_
Leave the `o-video` advertising code where it is, but find a way to pass all the targeting form `o-ads` to `o-video`. 
The only theoretical race condition that might happen is that `o-ads` is not initialised before the `o-video` init event has been emitted, which will result in less accurate targeting

_Idea 3:_
I have not got any more ideas but would really appreciate feedback and any possible solutions and opinions.

**Comment by wheresrhys** [comment]
It'd be good to see markup examples for both solutions

**Comment by VladDubrovskis** [comment]
@wheresrhys in terms of markup there would no difference. The only case where markup could be affected would be if we use data attribute (`data-o-ads-targeting`) to pass extra targeting to `o-ads` (per video specific data, e.g. ID). Which actually can be avoided if the event will pass the data (e.g. video id) to `o-ads`

**Comment by VladDubrovskis** [comment]
this is stalling at the moment as there are plenty of other things in advertising taking priority, and value it will be adding might not be beneficial to business at the moment. Basically we still want to do this but sometime in the future when more targeting parameters will be necessary by operations side.

**Comment by JakeChampion** [comment]
More than 4 years have passed, I think we can close this issue

Please re-open or comment on the issue if you think otherwise
