### ISSUE TITLE
FT video content briefly displayed before the pre-roll ad

### ISSUE THREAD

**Issue by timdavenportFT** [Financial-Times/o-video#50]
On web app click on video, and see: 1/ ~1 second of FT video content 2/ pre-roll video ad 3/ rest of FT video content
Next avoids this problem by: 1/ click on video (to start the load) 2/ play button appears later 3/ click on play button

Suspect this is due to pre-roll ad taking longer to download than FT video content ?
Perhaps ideal solution would be an interstitial with user friendly messaging that auto plays when ready ?

**Comment by rowanbeentje** [comment]
We think this has been addressed by https://github.com/Financial-Times/o-video/pull/54 .
