### ISSUE TITLE
Placeholder sometimes not showing in IE10

### ISSUE THREAD

**Issue by debugwand** [Financial-Times/o-video#69]
tested with https://origami-build.ft.com/v2/demos/o-video@2.3.9/placeholder on browserstack Win8/IE10, first visit no placeholder image, subsequent refreshes there is a placeholder image

**Comment by debugwand** [comment]
https://github.com/Financial-Times/o-video/pull/70

**Comment by notlee** [comment]
I'm not sure if this was solved in #70 or not, but as we no longer support IE10 I'm going to close this old issue :)
