### ISSUE TITLE
Fetch implementation provider

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-video#7]
jsonp is only one option for handling cross origin in ie9. Another option might be to use a proxy server in order to keep same origin or (as next is considering) a hybrid approach where CORS is used in most browsers, but if not supported then it goes via a proxy.

Given this, perhaps better than bundling o-fetch-jsonp in here would be to use `fetch` by default but provide an API to define a function to use to fetch content, which must implement something like the fetch API

**Comment by JakeChampion** [comment]
Is this still relevant now that we no longer use brightcove? If we want to use fetch, that is fine as we can pull it in via polyfill-service.

**Comment by wheresrhys** [comment]
would be good to just remove fetch-jsonp in the next major (presumably it's imminent with the o-colors etc update)

**Comment by JakeChampion** [comment]
cc @benbarnett @rowanbeentje

Would removing jsonp support cause issues on ft.com or the web app?

**Comment by rowanbeentje** [comment]
No problem removing it on the web app side! 👍

**Comment by benbarnett** [comment]
Does the fetch polyfill honour CORS for ~IE9? If not this will need more work, as the calls are now to `next-media-api.ft.com` which IE9 would still consider a distinct origin and therefore need something like jsonp.

**Comment by JakeChampion** [comment]
@matthew-andrews has answered this for us it seems. We should keep jsonp support -- https://github.com/github/fetch/issues/211#issuecomment-145067518

**Comment by wheresrhys** [comment]
But ie9 is not a js browser at FT any more

**Comment by benbarnett** [comment]
In which case we're probably good to remove... IE10+ supports CORS through `XMLHttpRequest` 🎊
