### ISSUE TITLE
iOS doesn't like firing progress events

### ISSUE THREAD

**Issue by rowanbeentje** [Financial-Times/o-video#75]
In a general review of progress events, it's noticeable that iOS Safari really doesn't like sending any progress events for the video element - looks like this isn't just us, eg https://github.com/videojs/video.js/issues/2309 .

As a result progress is only logged when another event is fired, or the viewer interacts manually with the player.

We could fix this by using some form of timer and using that to also trigger progress checks, probably in conjunction with a filter (the current progress tracking rounds to the nearest integer and then fires the event if it matches a list of "major" progress percentages - so the progress event can fire multiple times per second).

**Comment by rowanbeentje** [comment]
Thoughts @JakeChampion?  Any objections to me implementing a timer *everywhere* if I also filter out dupes, or should this be based on UA detection?

**Comment by rowanbeentje** [comment]
(Only running timer while video is playing, natch)

**Comment by JakeChampion** [comment]
Just checking I've understood correctly your proposal.

When video begins playing, start a timer which when triggered will fire a synthetic event solely to trick iOS Safari into firing a progress event for the video being played. When video stops playing, destroy the timer.

**Comment by rowanbeentje** [comment]
More that when the video begins playing, start a rAF/interval which will trigger a synthetic progress event track, as I'm not sure how easy it would be to trick the video into firing an event itself...

**Comment by JakeChampion** [comment]
I think we should try and use the native events if they work correctly and fallback to rAF progress event firing if our runtime detection has flagged native progress events as not working.

I haven't played a video on a iOS device in a while, do they carry on playing whilst the screen is lcoked/screensaver is shown? If so, animation frames would be paused meaning no synthetic progress events would fire.

**Comment by rowanbeentje** [comment]
How would runtime detection do that? :(

Just checked - video is paused when device is manually locked; it's possible to hit play on the lock screen but that looks like it only works properly for audio-only.  Yup, we'd lose progress there - we can't fix everything :)

**Comment by JakeChampion** [comment]
@rowanbeentje Did #83 resolve this?

**Comment by JakeChampion** [comment]
I'm assuming #83 resolved this 👍
