### ISSUE TITLE
Issues spotted prerelease

### ISSUE THREAD

**Issue by lc512k** [Financial-Times/o-video#9]
- Everything looks fine in:
1. Desktop Firefox (Mac)
2. Desktop Safari
3. Mobile Safari
4. iOS Chrome
5. iOS Firefox
- [ ] controls too wide in Chrome Canary. Everything else OK.
  <img width="335" alt="screen shot 2016-06-27 at 11 03 30" src="https://cloud.githubusercontent.com/assets/3425322/16376207/03136608-3c57-11e6-96fc-b2b330c6c664.png">
- [ ] Ad rolls but shows a black screen for the duration of the ad on android mobile chrome
  <img width="335" alt="screen shot 2016-06-27 at 11 03 30" src="https://cloud.githubusercontent.com/assets/3425322/16377198/8dbcd55a-3c5c-11e6-9cf9-bd6923861c79.png">
- Skip Ad button?

**Comment by AlbertoElias** [comment]
I'm going to close this, any lingering issues should go in separate issues
